steps:
  # 1) Build the image
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args:
      - build
      - --tag=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA
      - --tag=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:latest
      - --file=Dockerfile
      - .

 # 2a) Push the SHA-tagged image
  - name: 'gcr.io/cloud-builders/docker'
    id: push-sha
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA

 # 2b) Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: push-latest
    args:
     - push
     - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:latest

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --quiet

substitutions:
  _PROJECT_ID: personal-projects-460802
  _REGION: asia-south2
  _SERVICE: indian-place-generator
  _REPO: cloud-run-source-deploy

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
